# Generated by Django 5.1.7 on 2025-04-06 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_rename_worker_workerprofile_employerprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_posted_by', to='users.employerprofile')),
            ],
        ),
    ]
