# Generated by Django 5.1.7 on 2025-04-06 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobpost', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='employer_id',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='employer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_posted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
